### ISSUE TITLE
doesn't work with 1.3.4.3

### ISSUE THREAD

**Issue by sfofthings** [juliancwirko/meteor-s-grid#8]
Errors prevented startup:

   While loading plugin `compileStylus` from package
   `juliancwirko:s-grid`:
   plugin/compile-stylus.js:38:8: Object [object Object] has no
   method 'existsSync'
   at Package (plugin/compile-stylus.js:38:8)
   at <runJavaScript-35>:258:4
   at <runJavaScript-35>:265:3

   While running registerCompiler callback in package
   juliancwirko:s-grid:
   plugin/compile-stylus.js:16:10: undefined is not a function (at
   PACKAGES_FILE)

**Comment by juliancwirko** [comment]
Hi, there was some changes in new build's compile plugins. I think I need to update it. 

Btw. have you tried to use it as a package from Npm (https://www.npmjs.com/package/s-grid) ? You can use Npm packages in Meteor now. Maybe this will be a better way to use it. You just need to remember that you need Autoprefixer and Stylus installed in you Meteor App.

**Comment by juliancwirko** [comment]
on the Atmosphere there is fixed version [2.3.0](https://atmospherejs.com/juliancwirko/s-grid) , but I've mistakenly removed repo before pushing it so for now it is only on Atmosphere ;) anyway, I recommend using the grid as a package from Npm ;)
